# Generated by Django 3.2.3 on 2021-06-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
    ]
