# Generated by Django 3.2.3 on 2021-06-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_positions_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
