# Generated by Django 3.2.3 on 2021-07-25 20:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OptionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_or_put', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('long_or_short', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5)),
                ('expiration_date', models.DateField()),
                ('strike_price', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total_contracts', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if unknown', max_digits=4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.industry')),
                ('portfolio', models.ManyToManyField(to='assets.Portfolio')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.sector')),
            ],
        ),
        migrations.CreateModel(
            name='VerticalSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('BULL', 'Bull'), ('BEAR', 'Bear')], max_length=10)),
                ('credit_or_debit', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=20)),
                ('long_leg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='long_leg', to='assets.optionposition')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio')),
                ('short_leg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_leg', to='assets.optionposition')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='StockPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_or_short', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=5)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total_shares', models.DecimalField(decimal_places=4, max_digits=19)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectivePut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_put', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.optionposition')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio')),
                ('stock_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.stockposition')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ticker')),
            ],
        ),
        migrations.AddField(
            model_name='optionposition',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio'),
        ),
        migrations.AddField(
            model_name='optionposition',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ticker'),
        ),
        migrations.AddField(
            model_name='industry',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.sector'),
        ),
        migrations.CreateModel(
            name='Collar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_put', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='long_put', to='assets.optionposition')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio')),
                ('short_call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_call', to='assets.optionposition')),
                ('stock_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.stockposition')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='ButterflySpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('IRON CONDOR', 'Iron Condor')], max_length=20)),
                ('bear_spread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bear_spread', to='assets.verticalspread')),
                ('bull_spread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bull_spread', to='assets.verticalspread')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ticker')),
            ],
        ),
    ]
