# Generated by Django 3.2.3 on 2021-07-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionposition',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='stockposition',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='stockposition',
            name='total_shares',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
