# Generated by Django 3.2.3 on 2021-06-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('call_or_put', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('buy_or_sell', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('expiration_date', models.DateField()),
                ('strike_price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total_contracts', models.PositiveIntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total_shares', models.DecimalField(decimal_places=4, max_digits=19)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
