# Generated by Django 3.2.3 on 2021-06-24 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20210620_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio')),
            ],
            options={
                'ordering': ['-portfolio'],
            },
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ticker'),
        ),
        migrations.AlterField(
            model_name='stockposition',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ticker'),
        ),
    ]
