# Generated by Django 3.2.3 on 2021-07-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_optionposition_strike_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butterflyspread',
            name='types',
            field=models.CharField(choices=[('CREDIT', 'Iron Condor (Credit)')], max_length=25),
        ),
    ]
