# Generated by Django 3.2.3 on 2021-07-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20210726_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if not margin account', max_digits=4, null=True),
        ),
    ]
