# Generated by Django 3.2.3 on 2021-06-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20210624_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={},
        ),
    ]
