# Generated by Django 3.2.3 on 2021-07-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20210727_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='portfolio',
            field=models.ManyToManyField(blank=True, null=True, to='assets.Portfolio'),
        ),
    ]
