# Generated by Django 3.2.3 on 2021-08-05 12:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_butterflyspread_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionposition',
            old_name='entry_price',
            new_name='average_price',
        ),
        migrations.RemoveField(
            model_name='stockposition',
            name='entry_price',
        ),
        migrations.AddField(
            model_name='stockposition',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockposition',
            name='total_shares',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
