# Generated by Django 3.2.3 on 2021-06-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_ticker_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockposition',
            name='ticker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.ticker'),
        ),
    ]
