# Generated by Django 3.2.3 on 2021-07-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_ticker_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockposition',
            old_name='total_cost',
            new_name='entry_price',
        ),
    ]
