# Generated by Django 3.2.3 on 2021-07-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20210723_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='optionposition',
            name='buy_or_sell',
        ),
        migrations.AddField(
            model_name='optionposition',
            name='long_or_short',
            field=models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VerticalSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('BULL', 'Bull'), ('BEAR', 'Bear')], max_length=10)),
                ('credit_or_debit', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('NA', 'Not Applicable')], max_length=20)),
                ('long_leg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='long_leg', to='assets.optionposition')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio')),
                ('short_leg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_leg', to='assets.optionposition')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.sector')),
            ],
        ),
        migrations.CreateModel(
            name='ButterflySpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('IRON CONDOR', 'Iron Condor')], max_length=20)),
                ('bear_spread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bear_spread', to='assets.verticalspread')),
                ('bull_spread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bull_spread', to='assets.verticalspread')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='ticker',
            name='industry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assets.industry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='sector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assets.sector'),
            preserve_default=False,
        ),
    ]
