# Generated by Django 3.2.3 on 2021-07-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_rename_total_cost_stockposition_entry_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionposition',
            old_name='total_cost',
            new_name='entry_price',
        ),
    ]
